### ISSUE TITLE
Service Error 401002 CA certificate not found error

### ISSUE THREAD

**Issue by Shreyasnie** [rwatjen/AzureIoTDPSCertificates#3]
Hello,

I executed following steps

1) Create CA certificate using create cert chain.
2) Uploaded CA certificate to certificates section under DPS.
3) Generated verification code.
4) Generated verification certificate using verification code as common name using createverificationcert
5) uploaded verification certificate and verified successfully.
6)created group enrollment with Root certificate.
7)generated device specif pfx using createdevicecert
8)tried to provision device using device specific certificate it throws Service Error $01002 Certificate not found (.Net Simulated device)

**Comment by dusanruzicic** [comment]
Hi Shreyasnie,

You need to check that you are sending also certificate chain to DPS. The chain consists of intermediate certificates.
The constructor of class SecurityProviderX509Certificate is taking two parameters, device certificate and chain, you need to provide both.

I had the same problem and figured out that this was missing.

Best Regards,
Dusan

**Comment by rwatjen** [comment]
@Shreyasnie: If @dusanruzicic's suggestion did not help you, then please write again.
