### ISSUE TITLE
Issue with iothub_ll_client_x509_sample on Ubuntu 18.04 64-bit machine IoT SDKs

### ISSUE THREAD

**Issue by prohith46** [rwatjen/AzureIoTDPSCertificates#5]
Could build azure-iot-'C'-sdk along with the samples bundled with the sdk, but, ran into an issue while attempting to exectute iothub_ll_client_x509_sample under iothub_client samples.

connection string has been set with our x509 iothub connection string appropriately along with x509 certificate and private key using the device_ll_handle returned by IoTHubDeviceClient_LL_CreateFromConnectionString() as follows:

IoTHubDeviceClient_LL_SetOption(device_ll_handle, OPTION_X509_CERT, x509certificate);
IoTHubDeviceClient_LL_SetOption(device_ll_handle, OPTION_X509_PRIVATE_KEY, x509privatekey);

Upon executing iothub_ll_client_x509_sample, I get the following errors:

Creating IoTHub handle
Sending message 1 to IoTHub
Error: Time:Mon Sep 9 12:00:24 2019 File:/home/administrator/Documents/docker/iot-agent/azure-iot-sdk-c/c-utility/adapters/x509_openssl.c Func:log_ERR_get_error Line:29 Failure creating private key evp_key
Error: Time:Mon Sep 9 12:00:24 2019 File:/home/administrator/Documents/docker/iot-agent/azure-iot-sdk-c/c-utility/adapters/x509_openssl.c Func:log_ERR_get_error Line:36 [0] error:0908F070:PEM routines:get_header_and_data:short header
Error: Time:Mon Sep 9 12:00:24 2019 File:/home/administrator/Documents/docker/iot-agent/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:log_ERR_get_error Line:428 unable to use x509 authentication
Error: Time:Mon Sep 9 12:00:24 2019 File:/home/administrator/Documents/docker/iot-agent/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1253 Failed creating the OpenSSL instance.
Error: Time:Mon Sep 9 12:00:24 2019 File:/home/administrator/Documents/docker/iot-agent/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:1005 Error: io_open failed
Error: Time:Mon Sep 9 12:00:24 2019 File:/home/administrator/Documents/docker/iot-agent/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2262 failure connecting to address iot-hub-dev-north-europe-1.azure-devices.net.

Would anyone please suggest on what might possibley be causing these errors and how to resolve them?
For what it's worth, this issue is not observed on Windows 10 machine.

**Comment by rwatjen** [comment]
Hi,
This issue is not about my DPS certificate tool, but seems to be about the IoT hub C SDK. 

You should raise the issue there.
https://github.com/Azure/azure-iot-sdk-c
